{{- $plaformIsSet := printf "%s" (required "Platform needs to be set to kubernetes or openshift" (include "dynatrace-oneagent-operator.plaformSet" .))}}
{{- if eq .Values.platform "kubernetes" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-oneagent-operator
  namespace: {{ .Release.Namespace }}
{{ end }}
