apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: oneagents.dynatrace.com
  labels:
    app: {{ template "dynatrace-oneagent.name" . }}
    chart: {{ template "dynatrace-oneagent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: dynatrace.com
  names:
    kind: OneAgent
    listKind: OneAgentList
    plural: oneagents
    singular: oneagent
  scope: Namespaced
  version: v1alpha1
