apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: dynatrace-oneagent-operator
  labels:
    dynatrace: operator
    operator: oneagent
    app: {{ template "dynatrace-oneagent.name" . }}
    chart: {{ template "dynatrace-oneagent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: dynatrace-oneagent-operator
roleRef:
  kind: Role
  name: dynatrace-oneagent-operator
  apiGroup: rbac.authorization.k8s.io
