apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dynatrace-oneagent-operator
  labels:
    dynatrace: operator
    operator: oneagent
    app: {{ template "dynatrace-oneagent.name" . }}
    chart: {{ template "dynatrace-oneagent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - dynatrace.com
  resources:
  - oneagents
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dynatrace.com
  resources:
  - oneagents/finalizers
  verbs:
  - update
