{{- if and (or .Values.apiToken .Values.paasToken) (not (and .Values.apiToken .Values.paasToken)) -}}
{{ fail "Dynatrace: apiToken and paasToken are both required values." }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dynatrace-oneagent.fullname" . }}-tokens
  labels:
    app: {{ template "dynatrace-oneagent.name" . }}
    chart: {{ template "dynatrace-oneagent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  apiToken: {{ .Values.apiToken | b64enc | quote }}
  paasToken: {{ .Values.paasToken | b64enc | quote }}
type: Opaque
