apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-oneagent-operator
  labels:
    app: {{ template "dynatrace-oneagent.name" . }}
    chart: {{ template "dynatrace-oneagent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
