# Default values for dynatrace-oneagent-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  image:
    
oneagent:
  name: "oneagent"
  apiUrl:

secret:
  name: "oneagent"
  apiToken:
  paasToken:

deployerHelm:
  image:

operatorServiceAccount: null
oneagentServiceAccount: null
configurationServiceAccount: null