apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: oneagents.dynatrace.com
spec:
  group: dynatrace.com
  names:
    kind: OneAgent
    listKind: OneAgentList
    plural: oneagents
    singular: oneagent
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-oneagent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dynatrace-oneagent-operator
  template:
    metadata:
      labels:
        name: dynatrace-oneagent-operator
    spec:
      containers:
        - name: dynatrace-oneagent-operator
          image: 172.16.113.133:30000/dynatrace-oneagent-operator
          command:
          - dynatrace-oneagent-operator
          imagePullPolicy: Always
