{{- $platformIsSet := printf "%s" (required "Platform needs to be set to kubernetes or openshift" (include "dynatrace-oneagent-operator.platformSet" .))}}
{{- if eq .Values.platform "openshift" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-oneagent-operator.commonlabels" . | nindent 4 }}
rules:
  - apiGroups:
      - dynatrace.com
    resources:
      - oneagents
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - dynatrace.com
    resources:
      - oneagents/finalizers
      - oneagents/status
    verbs:
      - update
  - apiGroups:
      - networking.istio.io
    resources:
      - serviceentries
      - virtualservices
    verbs:
      - get
      - list
      - create
      - update
      - delete
{{ end }}