{{- $plaformIsSet := printf "%s" (required "Platform needs to be set to kubernetes or openshift" (include "dynatrace-oneagent-operator.plaformSet" .))}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-oneagent-operator
  labels:
    dynatrace: operator
    operator: oneagent
subjects:
  - kind: ServiceAccount
    name: dynatrace-oneagent-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: dynatrace-oneagent-operator
  apiGroup: rbac.authorization.k8s.io